[package]
name = "iocraft"
version = "0.7.14"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Create beautifully crafted CLI programs and text output with a declarative React-like Rust API."
repository = "https://github.com/ccbrown/iocraft"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
taffy = { version = "0.5.2", default-features = false, features = ["std", "flexbox", "taffy_tree"] }
iocraft-macros = { version = "0.2.3", path = "../iocraft-macros" }
bitflags = "2.6.0"
unicode-width = "0.1.13"
generational-box = "0.5.6"
any_key = "0.1.1"

[dev-dependencies]
indoc = "2"
smol = "2.0.1"
smol-macros = "0.1.1"
macro_rules_attribute = "0.2.0"
